<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find bubbles_description)/urdf/bubbles_snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>

  <!-- Parameters -->
  <xacro:property name="mass" value="12"/>
  <xacro:property name="volume" value="0.011054"/>
  <xacro:property name="cog" value="0 0.005 -.03"/>
  <xacro:property name="cob" value="0 0 0"/>
  <xacro:property name="rho" value="1028"/>

  <xacro:property name="x_size" value="0.448"/>
  <xacro:property name="y_size" value="0.2384"/>
  <xacro:property name="z_size" value="0.28066"/>

  <xacro:property name="equivalent_radius" value="${0.5*z_size}"/>

  <xacro:macro name="bubbles_base" params="namespace debug inertial_reference_frame">

  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="${cog}" rpy="0 0 0"/>
      <inertia ixx="0.26" ixy=".001" ixz=".02"
               iyy="0.40" iyz=".001"
               izz="0.35" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".35 .2 .1"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz=".1 .15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz="-.1 .15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz=".1 -.15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz="-.1 -.15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz="-.1 -.15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </visual>

    <visual>
      <origin xyz="-.225 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".1 .05 .05"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".35 .2 .1"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz=".1 .15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz="-.1 .15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz=".1 -.15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz="-.1 -.15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz="-.1 -.15 0" rpy="0 0 0"/>
      <geometry>
        <box size=".05 .1 .05"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz="-.225 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".1 .05 .05"/>
      </geometry>
    </collision>
    
  </link>

  <gazebo reference="${namespace}/base_link">
    <selfCollide>false</selfCollide>
  </gazebo>

    <!-- Set up hydrodynamic plugin -->
    <gazebo>
      <plugin name="${namespace}_uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
        <fluid_density>${rho}</fluid_density>
        <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
        <debug>${debug}</debug>
        <link name="${namespace}/base_link">
          <neutrally_buoyant>0</neutrally_buoyant>
          <volume>${volume}</volume>
          <box>
            <width>${y_size}</width>
            <length>${x_size}</length>
            <height>${z_size}</height>
          </box>
          <center_of_buoyancy>${cob}</center_of_buoyancy>
          <hydrodynamic_model>
            <type>fossen</type>
            <added_mass>
              3.899   -0.034  -0.517  0.043   -0.828  -0.039
              -0.034  6.110   0.256   2.047   -0.029  0.314
              -0.517  0.256   18.300  0.031   -1.932  0.054
              0.043   2.047   0.031   1.675   -0.050  0.105
              -0.828  -0.029  -1.932  -0.050  2.213   -0.006
              -0.039  0.314   0.054   0.105   -0.006  0.622
            </added_mass>
            <linear_damping>
              -9.352  -8.685  -91.050 -10 -10 -5
            </linear_damping>
            <quadratic_damping>
              -93.528 -124.066 -227.626 -20 -20 -15
            </quadratic_damping>
          </hydrodynamic_model>
        </link>
      </plugin>
    </gazebo>

    <xacro:include filename="$(find bubbles_description)/urdf/bubbles_thrusters.xacro"/>
    <xacro:include filename="$(find bubbles_description)/urdf/bubbles_sensors.xacro"/>

  </xacro:macro>

</robot>
